[package]
name = "d7050e"
version = "0.1.0"
authors = ["viktorfrom"]
edition = "2018"

[dependencies]
nom = "5.0.1"
lazy_static= "1.4.0"
nom_locate = "1.0.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm8-0" }
structopt = { version = "0.3", default-features = false }